<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Vj7FCJ\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Vj7FCJ/ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container2Vj7FCJ.legacy');

    return;
}

if (!\class_exists(ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\Container2Vj7FCJ\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \Container2Vj7FCJ\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => '2Vj7FCJ',
    'container.build_id' => '8651e52e',
    'container.build_time' => 1585931622,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Vj7FCJ');
