<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRx0Fs6\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRx0Fs6/testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSRx0Fs6.legacy');

    return;
}

if (!\class_exists(testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSRx0Fs6\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \ContainerSRx0Fs6\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => 'SRx0Fs6',
    'container.build_id' => '28876d0c',
    'container.build_time' => 1585931535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRx0Fs6');
