<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'saam_lorem_ipsum.ipsum_api_controller' shared service.

$this->services['saam_lorem_ipsum.ipsum_api_controller'] = $instance = new \SaaM\LoremIpsumBundle\Controller\IpsumApiController(($this->services['saam_lorem_ipsum.saam_ipsum'] ?? $this->load('getSaamLoremIpsum_SaamIpsumService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
    'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
    'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
    'router' => ['services', 'router', 'getRouterService', false],
], [
    'http_kernel' => '?',
    'parameter_bag' => '?',
    'request_stack' => '?',
    'router' => '?',
]))->withContext('saam_lorem_ipsum.ipsum_api_controller', $this));

return $instance;
