<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRIhy21x\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRIhy21x/testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRIhy21x.legacy');

    return;
}

if (!\class_exists(testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRIhy21x\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \ContainerRIhy21x\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => 'RIhy21x',
    'container.build_id' => 'cd584dcb',
    'container.build_time' => 1585950879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRIhy21x');
