<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF0VghoE\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF0VghoE/ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerF0VghoE.legacy');

    return;
}

if (!\class_exists(ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerF0VghoE\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \ContainerF0VghoE\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => 'F0VghoE',
    'container.build_id' => '700c5a11',
    'container.build_time' => 1585952349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF0VghoE');
