<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFKCchc5\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFKCchc5/testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFKCchc5.legacy');

    return;
}

if (!\class_exists(testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFKCchc5\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \ContainerFKCchc5\testsSaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => 'FKCchc5',
    'container.build_id' => 'b42a2ad1',
    'container.build_time' => 1585926161,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFKCchc5');
