<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'saam_lorem_ipsum.saam_ipsum' shared service.

return $this->services['saam_lorem_ipsum.saam_ipsum'] = new \SaaM\LoremIpsumBundle\SaaMIpsum(new \SaaM\LoremIpsumBundle\SaaMWordProvider(), true, 3);
