<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCbegc5G\SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCbegc5G/SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCbegc5G.legacy');

    return;
}

if (!\class_exists(SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCbegc5G\SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \ContainerCbegc5G\SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => 'Cbegc5G',
    'container.build_id' => 'c8bc90b3',
    'container.build_time' => 1585930883,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCbegc5G');
