<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP1qWc8t\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP1qWc8t/ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerP1qWc8t.legacy');

    return;
}

if (!\class_exists(ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerP1qWc8t\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \ContainerP1qWc8t\ControllerSaaM_LoremIpsumBundle_Tests_Controller_SaaMLoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => 'P1qWc8t',
    'container.build_id' => 'ce8a072a',
    'container.build_time' => 1585931975,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP1qWc8t');
