<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRft6y3w\SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRft6y3w/SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRft6y3w.legacy');

    return;
}

if (!\class_exists(SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRft6y3w\SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \ContainerRft6y3w\SaaM_LoremIpsumBundle_Tests_SaaMLoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => 'Rft6y3w',
    'container.build_id' => '56e717ad',
    'container.build_time' => 1585931065,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRft6y3w');
